# I\. Setup and Album Title Inspection

In [1]:
# Standard library imports
import os
from datetime import datetime

# Third-party imports
import numpy as np
import pandas as pd

# SETUP & CONFIGURATION
os.chdir("/work")
print(os.listdir("./pipeline"))

# Show all columns (no truncation)
pd.set_option("display.max_columns", None)

['1.1.TMDB 2015-2025.csv', '2.2.MUSICBRAINZ_mv_tmdb_soundtrack_album_artist_bridge_2015_2025.csv', '2.2.MUSICBRAINZ_mv_tmdb_soundtrack_artist_spine_2015_2025.csv', '3.2.Albums_official_df.csv', '3.2.Artists_official_df.csv', '3.2.Tracks_official_df.csv', '3.2.Wide_official_df.csv', '3.3.Albums_deduped_df.csv', '3.3.Artists_deduped_df.csv', '3.3.Tracks_deduped_df.csv', '3.3.Wide_deduped_df.csv', '3.4.Albums_canonical_identified_df.csv', '3.4.Artists_canonical_identified_df.csv', '3.4.Tracks_canonical_identified_df.csv', '3.4.Wide_canonical_identified_df.csv', '3.5.Albums_exploded_genre.csv', '3.5.Artists_exploded_genre.csv', '3.5.Tracks_exploded_genre.csv', '3.5.Wide_exploded_genre.csv', '3.6.Albums_vote_count_analysis.csv', '3.6.Artists_vote_count_analysis.csv', '3.6.Tracks_vote_count_analysis.csv', '3.6.Wide_vote_count_analysis.csv', '3.7.Albums_composer_analysis.csv', '3.7.Artists_composer_analysis.csv', '3.7.Tracks_composer_analysis.csv', '3.7.Wide_composer_analysis.csv', '4.1.1.Alb

In [2]:
# Load the albums dataframe

album_df = pd.read_csv("./pipeline/2.1.MUSICBRAINZ_mv_tmdb_soundtrack_album_spine_2015_2025.csv")

# Display initial data inspection
display(album_df.head())
display(album_df.columns)

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,film_imdb_id,film_wikidata_id,film_countries,film_year,film_release_date,film_popularity,film_budget,film_revenue,film_studios,film_director,film_soundtrack_composer_raw,film_top_cast,film_keywords,film_ingested_at,match_method,soundtrack_type,notes,matched_at,release_group_id,release_group_mbid,album_title,rg_primary_type,rg_secondary_types,release_id,release_mbid,release_title,release_status,release_packaging,barcode,release_language,release_script,release_comment,album_us_release_date,album_us_release_year,album_us_release_month_min_observed,album_us_release_day_min_observed,us_date_has_missing_month,us_date_has_missing_day,us_any_event_missing_month,us_any_event_missing_day,rg_tags_text,release_tags_text,label_names,label_mbids,label_tags_text,rg_rating,rg_rating_count,release_meta_date_added,release_meta_info_url,release_meta_amazon_asin,release_meta_cover_art_presence
0,216015,Fifty Shades of Grey,False,125,"Drama, Romance, Thriller",5.875,12222,R,Fifty Shades of Grey,English,tt2322441,Q14566553,United States of America,2015,2015-02-11,18.4171,40000000,569651467,"Universal Pictures, Focus Features, Michael De...",Sam Taylor-Johnson,"Danny Elfman, Ellie Goulding, The Weeknd","Dakota Johnson, Jamie Dornan, Jennifer Ehle, E...","bad smell, based on novel or book, eroticism, ...",2026-01-19 01:36:05.016 -0500,imdb_exact,songs,NaN,2026-01-25 02:45:25.371 -0500,1479583,85852629-ce4c-4bb8-8d4a-50299d56a06c,Fifty Shades of Grey: Original Motion Picture ...,Album,Soundtrack,1548281.0,bdcaa988-1e80-446b-8e15-39b42255c4ed,Fifty Shades of Grey: Original Motion Picture ...,Official,NaN,6.025472e+11,English,Latin,NaN,2015-02-10,2015.0,2.0,10.0,False,False,False,False,contemporary r&b | pop | blues | contemporary ...,soundtrack,Republic Records | Universal Studios,9e4d8965-4fa4-4ce9-a48a-6db90769aa05 | e0ecd90...,NaN,NaN,NaN,2015-01-09 19:01:19.035 -0500,https://www.amazon.com/gp/product/B00S17FT82,NaN,present
1,216015,Fifty Shades of Grey,False,125,"Drama, Romance, Thriller",5.875,12222,R,Fifty Shades of Grey,English,tt2322441,Q14566553,United States of America,2015,2015-02-11,18.4171,40000000,569651467,"Universal Pictures, Focus Features, Michael De...",Sam Taylor-Johnson,"Danny Elfman, Ellie Goulding, The Weeknd","Dakota Johnson, Jamie Dornan, Jennifer Ehle, E...","bad smell, based on novel or book, eroticism, ...",2026-01-19 01:36:05.016 -0500,imdb_exact,score,NaN,2026-01-25 02:45:25.371 -0500,1494030,fa7aa3a0-3de5-4273-bbb4-cfc13dbf9f1e,Fifty Shades of Grey: Original Motion Picture ...,Album,Soundtrack,1566447.0,dd34d90a-52ff-445c-8221-d03a6f876b24,Fifty Shades of Grey: Original Motion Picture ...,Official,Jewel Case,6.025472e+11,English,Latin,NaN,2015-02-17,2015.0,2.0,17.0,False,False,False,False,score,NaN,Republic Records | Universal,1391bdc7-a22c-48a4-a5fb-e7b8ef6ce143 | e0ecd90...,alejandra guzman | clean up | es 2003 | sólo e...,NaN,NaN,2015-02-16 09:22:51.239 -0500,https://www.amazon.com/gp/product/B00S9303ZM,B00S9303ZM,present
2,150689,Cinderella,False,105,"Romance, Fantasy, Family, Drama",6.826,7294,PG,Cinderella,English,tt1661199,Q15046091,United Kingdom / United States of America,2015,2015-03-06,11.8041,95000000,543514353,"Walt Disney Pictures, Genre Films, Beagle Pug ...",Kenneth Branagh,Patrick Doyle,"Lily James, Cate Blanchett, Richard Madden, St...","magic, kingdom, fairy tale, prince, royalty",2026-01-19 01:36:05.016 -0500,imdb_exact,unknown,NaN,2026-01-25 02:45:25.371 -0500,1504629,412fdd65-c3f8-40fe-a420-8b438e048915,Cinderella,Album,Soundtrack,1579787.0,5da9400f-7f0c-45f3-8e78-fe98f17aa43e,Cinderella,Official,NaN,NaN,English,Latin,NaN,2015-03-10,2015.0,3.0,10.0,False,False,False,False,classical | film score,film score,Walt Disney Records,1c50034a-5c92-41a4-95ad-0acb7ea4686f,score | soundtrack | soundtrack label | classi...,NaN,NaN,2015-03-16 23:29:40.780 -0400,https://www

Index(['tmdb_id', 'film_title', 'film_adult', 'film_runtime_min',
       'film_genres', 'film_rating', 'film_vote_count', 'film_mpaa_rating',
       'film_original_title', 'film_language_name', 'film_imdb_id',
       'film_wikidata_id', 'film_countries', 'film_year', 'film_release_date',
       'film_popularity', 'film_budget', 'film_revenue', 'film_studios',
       'film_director', 'film_soundtrack_composer_raw', 'film_top_cast',
       'film_keywords', 'film_ingested_at', 'match_method', 'soundtrack_type',
       'notes', 'matched_at', 'release_group_id', 'release_group_mbid',
       'album_title', 'rg_primary_type', 'rg_secondary_types', 'release_id',
       'release_mbid', 'release_title', 'release_status', 'release_packaging',
       'barcode', 'release_language', 'release_script', 'release_comment',
       'album_us_release_date', 'album_us_release_year',
       'album_us_release_month_min_observed',
       'album_us_release_day_min_observed', 'us_date_has_missing_month',
       

# II\. Unofficial Album Exploration

In [3]:
# =========================
# Inspect + summarize "unofficial" albums (by release_status)
# Assumes: album_df exists
# =========================

# 1) Quick coverage: how many rows + how many unique release_groups by status?
status_cols = ["release_status", "release_group_mbid", "album_title", "tmdb_id", "film_title", "film_year", "album_us_release_date"]

# Make sure the key columns exist (won't error if some are missing)
status_cols = [c for c in status_cols if c in album_df.columns]

print("Rows in album_df:", len(album_df))
print("\nRelease status distribution (rows):")
display(album_df["release_status"].fillna("(missing)").value_counts(dropna=False))

# Unique release_groups per status
rg_per_status = (
    album_df.assign(release_status=album_df["release_status"].fillna("(missing)"))
           .groupby("release_status")["release_group_mbid"]
           .nunique()
           .sort_values(ascending=False)
           .to_frame("unique_release_groups")
)
print("\nRelease status distribution (unique release_group_mbid):")
display(rg_per_status)


Rows in album_df: 5209

Release status distribution (rows):


release_status
Official          5036
(missing)           89
Bootleg             53
Promotion           19
Withdrawn            7
Pseudo-Release       5
Name: count, dtype: int64


Release status distribution (unique release_group_mbid):


,unique_release_groups
release_status,
Official,4785
(missing),77
Bootleg,39
Promotion,15
Withdrawn,7
Pseudo-Release,5


In [4]:
# 2) Define what's "unofficial" (everything except Official)
album_df["release_status_clean"] = album_df["release_status"].fillna("(missing)")
unofficial_df = album_df.loc[album_df["release_status_clean"] != "Official"].copy()

print("\nUnofficial rows:", len(unofficial_df))
print("Unofficial unique release_group_mbids:", unofficial_df["release_group_mbid"].nunique())
print("Unofficial unique tmdb_ids:", unofficial_df["tmdb_id"].nunique())


Unofficial rows: 173
Unofficial unique release_group_mbids: 143
Unofficial unique tmdb_ids: 171


In [5]:
# 3) Breakdown of unofficial types (rows + unique release_groups)
unofficial_breakdown = (
    unofficial_df.groupby("release_status_clean")
                 .agg(
                     row_ct=("release_group_mbid", "size"),
                     unique_release_groups=("release_group_mbid", "nunique"),
                     unique_tmdb_ids=("tmdb_id", "nunique"),
                 )
                 .sort_values(["unique_release_groups", "row_ct"], ascending=False)
)
print("\nUnofficial breakdown:")
display(unofficial_breakdown)


Unofficial breakdown:


,row_ct,unique_release_groups,unique_tmdb_ids
release_status_clean,,,
(missing),89,77,88
Bootleg,53,39,52
Promotion,19,15,19
Withdrawn,7,7,7
Pseudo-Release,5,5,5


Findings: This breakdown confirms that the vast majority of records in the MusicBrainz export are standard releases, with only a small fraction flagged as bootlegs, promotions, withdrawn titles, or pseudo\-releases\. In other words, edge\-case release types exist, but they are not materially driving the dataset\. That gives us confidence that our album spine is largely composed of legitimate commercial soundtrack releases rather than archival artifacts or non\-standard entries\.

In [6]:
# 4) How much would we drop if we filter them out?
total_rgs = album_df["release_group_mbid"].nunique()
unofficial_rgs = unofficial_df["release_group_mbid"].nunique()

print("\nImpact if we remove unofficial:")
print(f"- % of rows dropped: {len(unofficial_df) / len(album_df):.2%}")
print(f"- % of unique release_groups dropped: {unofficial_rgs / total_rgs:.2%}")


Impact if we remove unofficial:
- % of rows dropped: 3.32%
- % of unique release_groups dropped: 2.90%


In [7]:
# 5) Spot-check: show a few examples per unofficial status
# (useful for sanity-checking what kinds of albums these are)
cols_for_view = ["release_status_clean", "album_title", "release_group_mbid", "rg_primary_type",
                            "album_us_release_date", "release_status", "release_packaging",
                            "rg_tags_text", "label_names", "match_method",
                            "film_title", "film_year", "tmdb_id"
                            ]

for status in unofficial_df["release_status_clean"].value_counts().index:
    print(f"\n--- Examples: {status} ---")
    display(
        unofficial_df.loc[unofficial_df["release_status_clean"] == status, cols_for_view]
                    .drop_duplicates(subset=[c for c in ["release_group_mbid", "tmdb_id"] if c in unofficial_df.columns])
                    .head(15)
    )





--- Examples: (missing) ---


,release_status_clean,album_title,release_group_mbid,rg_primary_type,album_us_release_date,release_status,release_packaging,rg_tags_text,label_names,match_method,film_title,film_year,tmdb_id
45,(missing),Vice (Original Motion Picture Soundtrack),677c466b-e852-4350-b375-970c449d4a0a,Album,2015-05-30,NaN,NaN,ambient | electronic,Metropolis Movie Music,imdb_exact,Vice,2015,307663
212,(missing),Wings,3045b83b-5014-49ec-ac78-03893ce5991a,Single,NaN,NaN,NaN,NaN,NaN,imdb_exact,We Are Family,2016,391700
538,(missing),Ma Rainey's Black Bottom,ca267058-e26f-4db9-8b42-145b0f8ca489,Album,2020-01-01,NaN,NaN,blues,Masterworks | Milan | Netflix,imdb_exact,Ma Rainey's Black Bottom,2020,615667
915,(missing),Mudhal Nee Mudivum Nee,c6ac7ec7-fcda-412e-b13c-301949c08e25,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Mudhal Nee Mudivum Nee,2022,861996
918,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2019,583755
919,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2020,610908
953,(missing),Fake News (Soundtrack),785004df-433c-4537-b1f4-4fa7907bdf2d,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Fake News,2021,735716
975,(missing),We Are Still Here (Original Motion Picture Sou...,065a3a89-1fd2-4482-b73f-24a4d8dee4b7,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,We Are Still Here,2015,291272
1020,(missing),Heaven,bccfef28-9f1d-44e6-ae00-5cfdb34d836f,NaN,NaN,NaN,NaN,NaN,Umbrella Artist Productions,title_contains_strict,Heaven,2018,552362
1053,(missing),"Good Night, Knight OST",514437dc-d0f8-4b91-93d2-e6795fdfa38a,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Good Night,2023,1090969



--- Examples: Bootleg ---


,release_status_clean,album_title,release_group_mbid,rg_primary_type,album_us_release_date,release_status,release_packaging,rg_tags_text,label_names,match_method,film_title,film_year,tmdb_id
815,Bootleg,Night School,67a7e6d3-5eb6-4859-9dfa-6a54c7e13e66,Album,NaN,Bootleg,NaN,NaN,The Master Cylinder,title_contains_strict,Night School,2018,454293
866,Bootleg,Guava Island Soundtrack,70d20859-fdc0-4cdd-a035-d9d1e38dd0c1,EP,NaN,Bootleg,NaN,NaN,NaN,title_contains_strict,Guava Island,2019,543343
907,Bootleg,"Merry Christmas, Data Design (Original Soundtr...",9c14143a-9a6f-4dce-8e2f-b0fb74d68e63,Album,NaN,Bootleg,NaN,NaN,NaN,title_contains_strict,Merry Christmas,2023,894958
908,Bootleg,"Merry Christmas, Data Design (Original Soundtr...",9c14143a-9a6f-4dce-8e2f-b0fb74d68e63,Album,NaN,Bootleg,NaN,NaN,NaN,title_contains_strict,Merry Christmas,2024,890116
910,Bootleg,Rage,7f5c32eb-b083-4921-90b2-51344f633cac,Album,NaN,Bootleg,NaN,NaN,The Master Cylinder,title_contains_strict,Rage,2016,359344
911,Bootleg,Rage,7f5c32eb-b083-4921-90b2-51344f633cac,Album,NaN,Bootleg,NaN,NaN,The Master Cylinder,title_contains_strict,Rage,2020,694096
1114,Bootleg,The Beast Within,c8ebc3dd-fc3b-479a-af71-090a76fade6e,Album,NaN,Bootleg,NaN,NaN,NaN,title_contains_strict,The Beast Within,2024,1300962
1151,Bootleg,My Little Pony: Equestria Girls - Magical Movi...,0444e93d-41be-414f-847c-3c9508201c3f,Album,NaN,Bootleg,NaN,NaN,NaN,title_contains_strict,My Little Pony: Equestria Girls - Magical Movi...,2017,527429
1158,Bootleg,Agony,860f9004-35df-4c92-af40-c3eb4925c6be,Album,NaN,Bootleg,NaN,NaN,The 16-bit Audiophile Project,title_contains_strict,Agony,2016,384086
1265,Bootleg,Among Us,535e1cc6-faad-42cf-a1bc-eb2d9f9ad2ec,Other,NaN,Bootleg,NaN,soundtrack,NaN,title_contains_strict,Among Us,2017,707080



--- Examples: Promotion ---


,release_status_clean,album_title,release_group_mbid,rg_primary_type,album_us_release_date,release_status,release_packaging,rg_tags_text,label_names,match_method,film_title,film_year,tmdb_id
822,Promotion,Arsenal,b4e6f0f7-ece6-485d-9166-60ac0965514f,Album,NaN,Promotion,Cardboard/Paper Sleeve,electronic,I Own You Records,title_contains_strict,Arsenal,2017,388202
865,Promotion,Dead in the Water,50f4ae05-820a-46fa-b2c5-d308da41640b,Album,NaN,Promotion,NaN,NaN,[no label],title_contains_strict,Dead in the Water,2018,551910
1108,Promotion,Playing God,a0c30f68-9c93-491c-ab91-c8a9dfda57a6,Album,NaN,Promotion,NaN,NaN,[no label],title_contains_strict,Playing God,2024,1320467
1856,Promotion,Freestyle,28347912-017b-42f8-b1e7-1b12a975291c,Single,NaN,Promotion,Other,NaN,NaN,title_contains_strict,Freestyle,2022,892494
1920,Promotion,In My Dreams,13539200-9378-4ea5-977b-0e126a8f6fa7,Album,2014-01-01,Promotion,Digipak,NaN,Momentum RLP Records,title_contains_strict,In My Dreams,2015,266353
1943,Promotion,Happily Never After Bonus Soundtrack CD,0e4c8400-4fd8-4428-a350-891912a966ab,Album,NaN,Promotion,NaN,NaN,NaN,title_contains_strict,Happily Never After,2017,522328
3031,Promotion,Star Wars: The Rise of Skywalker: Original Mot...,e3e74153-b7b0-466e-9e69-b587a5ead9cc,Album,2019-01-01,Promotion,NaN,soundtrack | classical | film | film score | o...,NaN,imdb_exact,Star Wars: The Rise of Skywalker,2019,181812
3467,Promotion,Dead in the Water,50f4ae05-820a-46fa-b2c5-d308da41640b,Album,NaN,Promotion,NaN,NaN,[no label],title_contains_strict,Dead in the Water,2021,786302
3690,Promotion,Playing God,a0c30f68-9c93-491c-ab91-c8a9dfda57a6,Album,NaN,Promotion,NaN,NaN,[no label],title_contains_strict,Playing God,2020,759930
3691,Promotion,Playing God,a0c30f68-9c93-491c-ab91-c8a9dfda57a6,Album,NaN,Promotion,NaN,NaN,[no label],title_contains_strict,Playing God,2021,717693



--- Examples: Withdrawn ---


,release_status_clean,album_title,release_group_mbid,rg_primary_type,album_us_release_date,release_status,release_packaging,rg_tags_text,label_names,match_method,film_title,film_year,tmdb_id
642,Withdrawn,Doctor Strange in the Multiverse of Madness,176b5720-1680-4783-8e94-3046fae2a421,Album,2022-05-04,Withdrawn,NaN,classical,Hollywood Records | Marvel Music,imdb_exact,Doctor Strange in the Multiverse of Madness,2022,453395
2517,Withdrawn,The Marvels: Original Motion Picture Soundtrack,4afa8579-467e-4676-a168-5f6494c65c53,Album,NaN,Withdrawn,NaN,NaN,Hollywood Records,title_contains_strict,The Marvels,2023,609681
3081,Withdrawn,Daniel Isn’t Real,623e2354-a33c-41b7-9626-109a48be83eb,Album,NaN,Withdrawn,NaN,ambient | classical | electronic | modern clas...,Deutsche Grammophon,imdb_exact,Daniel Isn't Real,2019,537788
3227,Withdrawn,The Batman: Original Motion Picture Soundtrack,cacbb4e4-0580-4ace-a085-019bc8fe47b1,Album,2022-02-25,Withdrawn,NaN,classical | score | soundtrack,WaterTower Music,imdb_exact,The Batman,2022,414906
3711,Withdrawn,Smallfoot: Original Motion Picture Soundtrack,f7b60bd6-6ee1-4d12-a14a-a68d094686e0,Album,2018-09-28,Withdrawn,NaN,pop,WaterTower Music,title_contains_strict,Smallfoot,2018,446894
3851,Withdrawn,The Runner (Original Soundtrack),a997db62-f64c-4aab-8373-f959d685644c,Album,2022-01-01,Withdrawn,NaN,electronic | coldwave | drone | ebm | soundtra...,City Slang,title_contains_strict,The Runner,2022,887309
4194,Withdrawn,Rocky Aur Rani Kii Prem Kahaani,d109158e-f445-4cd4-b9b5-843ce748af2b,Album,2024-05-15,Withdrawn,NaN,NaN,Saregama,title_contains_strict,Rocky Aur Rani Kii Prem Kahaani,2023,848116



--- Examples: Pseudo-Release ---


,release_status_clean,album_title,release_group_mbid,rg_primary_type,album_us_release_date,release_status,release_packaging,rg_tags_text,label_names,match_method,film_title,film_year,tmdb_id
1241,Pseudo-Release,モンスターハンター 狩猟音楽集XX,564e9d17-1fb6-4c6b-9235-e8c371e1c7d5,Album,NaN,Pseudo-Release,Jewel Case,NaN,SULEPUTER,title_contains_strict,XX,2017,297160
2066,Pseudo-Release,Perfect Days OST,8625eb42-0451-45e2-99bb-2d40c503eff4,Album,NaN,Pseudo-Release,NaN,NaN,NaN,title_contains_strict,Perfect Days,2023,976893
2509,Pseudo-Release,スタジオジブリ「高畑勲」サントラBOX,9b710346-ec64-463f-9b09-361d799388ef,Album,NaN,Pseudo-Release,NaN,NaN,NaN,title_contains_strict,Box,2015,346757
4376,Pseudo-Release,ReLIFE オリジナルサウンドトラック,de655243-3975-4e8a-8b0f-a06fdec8a6b1,Album,NaN,Pseudo-Release,NaN,NaN,NaN,title_contains_strict,ReLIFE,2017,437620
4402,Pseudo-Release,Ratchet & Clank: Original Soundtrack,df81ab43-aa95-411b-b4a3-14095f56030c,Album,NaN,Pseudo-Release,NaN,NaN,Sony Computer Entertainment America,title_contains_strict,Ratchet & Clank,2016,234004


Findings: A closer look at non\-standard release\_status categories shows that they are heterogeneous and inconsistently applied\. Many “\(missing\)” entries correspond to legitimate soundtracks, while “Promotion,” “Withdrawn,” and “Pseudo\-Release” statuses often reflect distribution variants, alternate\-language representations, or release\-state artifacts rather than distinct soundtrack concepts\. Because these categories blur structural boundaries at the release\_group level, we opted to anchor the analytical spine exclusively to “Official” releases\. This ensures a clean, reproducible album universe, even if it excludes some edge\-case but potentially valid variants\.

In [8]:
# 6) Identify the "worst offenders" (unofficial release_groups linked to many films)
# (if you still have dupes around, this can show where unofficial data may be muddying links)
if {"release_group_mbid", "tmdb_id"}.issubset(unofficial_df.columns):
    unofficial_rg_multi = (
        unofficial_df.groupby("release_group_mbid")["tmdb_id"]
                     .nunique()
                     .sort_values(ascending=False)
    )
    print("\nUnofficial release_groups mapped to multiple tmdb_ids (top 20):")
    display(unofficial_rg_multi.head(20).to_frame("distinct_tmdb_ids"))

    # Show context for the top few
    top_unofficial_rgs = unofficial_rg_multi.head(5).index.tolist()
    print("\nContext rows for top unofficial dupes (top 5 release_groups):")
    display(
        unofficial_df.loc[unofficial_df["release_group_mbid"].isin(top_unofficial_rgs), cols_for_view]
                    .sort_values(["release_group_mbid"] + (["film_year"] if "film_year" in cols_for_view else []))
    )



Unofficial release_groups mapped to multiple tmdb_ids (top 20):


,distinct_tmdb_ids
release_group_mbid,
14fdc06f-9fbb-47ac-a546-fca0bde66331,5
7f5c32eb-b083-4921-90b2-51344f633cac,4
a0c30f68-9c93-491c-ab91-c8a9dfda57a6,3
dff756a1-c1a4-4b3e-ba86-282be5d602df,3
2a97a7f8-b9e7-4148-9e8e-753ab4621296,3
535e1cc6-faad-42cf-a1bc-eb2d9f9ad2ec,2
50f4ae05-820a-46fa-b2c5-d308da41640b,2
afcb10ed-832b-4b3f-8cd4-82f7a67e76ec,2
69255f10-e358-35c8-b944-4f1594201e1c,2



Context rows for top unofficial dupes (top 5 release_groups):


,release_status_clean,album_title,release_group_mbid,rg_primary_type,album_us_release_date,release_status,release_packaging,rg_tags_text,label_names,match_method,film_title,film_year,tmdb_id
918,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2019,583755
919,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2020,610908
3513,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2020,554371
3514,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2021,591222
3515,(missing),Limbo,14fdc06f-9fbb-47ac-a546-fca0bde66331,NaN,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Limbo,2023,1077670
1581,(missing),INSIDE,2a97a7f8-b9e7-4148-9e8e-753ab4621296,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Inside,2016,365995
4204,(missing),INSIDE,2a97a7f8-b9e7-4148-9e8e-753ab4621296,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Inside,2023,958196
4205,(missing),INSIDE,2a97a7f8-b9e7-4148-9e8e-753ab4621296,Album,NaN,NaN,NaN,NaN,NaN,title_contains_strict,Inside,2025,1225582
910,Bootleg,Rage,7f5c32eb-b083-4921-90b2-51344f633cac,Album,NaN,Bootleg,NaN,NaN,The Master Cylinder,title_contains_strict,Rage,2016,359344
3505,Bootleg,Rage,7f5c32eb-b083-4921-90b2-51344f633cac,Album,NaN,Bootleg,NaN,NaN,The Master Cylinder,title_contains_strict,Rage,2018,510228


Findings: A deeper dive into unofficial release\_groups reveals a more serious issue: several are linked to multiple distinct TMDB films, often due to generic titles \(e\.g\., Limbo, Inside, Rage\) and title\-based matching\. In some cases, a single release\_group is mapped to as many as five different films\. This many\-to\-many ambiguity confirms that non\-Official statuses introduce structural contamination into the film–album spine\. Restricting the dataset to Official releases is therefore not just a cleanliness preference, but a necessary step to prevent cross\-film linkage errors\.

# III\. Deleting it from relevant tables

### III\.1 Cleaning up the Album DataFrame

After confirming that non\-Official release groups introduce cross\-film ambiguity, the next step was to formalize their removal\. Rather than filtering implicitly downstream, we construct an explicit deletion list at the release\_group level\. This allows us to surgically remove problematic film–album links while preserving a clear audit trail of what was excluded and why\.

In [9]:
# 7) Create a deletion list you can apply later (wide_df, etc.)
# Each is a tuple: (release_group_mbid, tmdb_id)
unofficial_removed_links_rgid = list(
    unofficial_df.loc[:, ["release_group_id", "tmdb_id"]]
                    .dropna()
                    .drop_duplicates()
                    .itertuples(index=False, name=None) # Yields plain tuples of (release_group_id, tmdb_id) without index
)

# For these deletes, we only really need the release group id
unofficial_rgid_set = set(rg_id for rg_id, _tmdb in unofficial_removed_links_rgid)

print("Deletion list (release_group_id, tmdb_id):", len(unofficial_removed_links_rgid))
print("Unique release_group_id to delete from tracks:", len(unofficial_rgid_set))
print(unofficial_removed_links_rgid[:10])

Deletion list (release_group_id, tmdb_id): 173
Unique release_group_id to delete from tracks: 143
[(2755193, 307663), (1463713, 391700), (2596752, 615667), (2964242, 453395), (1045547, 454293), (1957589, 388202), (4259672, 551910), (3612486, 543343), (3294554, 894958), (3294554, 890116)]


Findings: This process identified 173 film–album link pairs corresponding to 143 unique release\_groups marked as non\-Official\. In practical terms, these represent structurally ambiguous or non\-canonical soundtrack mappings that would otherwise propagate into the track\-level dataset\. By isolating these release\_groups early, we prevent cross\-film contamination in the wide analytical layer and ensure that downstream listener metrics are attributed only to vetted, Official soundtrack albums\.

In [10]:
official_album_df = album_df[album_df["release_status_clean"] == "Official"].copy()

print("Rows before:", len(album_df))
print("Rows after (Official only):", len(official_album_df))

print("\nRelease status distribution (official df):")
display(official_album_df["release_status_clean"].value_counts(dropna=False))

official_album_df.to_csv(
    "./pipeline/3.2.Albums_official_df.csv",
    index=False
)


Rows before: 5209
Rows after (Official only): 5036

Release status distribution (official df):


release_status_clean
Official    5036
Name: count, dtype: int64

Findings: Filtering to release\_status\_clean == "Official" reduced the album layer from 5,209 to 5,036 rows — a net removal of 173 records\. This confirms that non\-Official releases represented a relatively small but non\-trivial portion of the dataset \(~3%\)\. After filtering, the album spine consists entirely of Official releases, providing a cleaner and more defensible foundation for downstream track\- and listener\-level analysis\.

In [11]:
set(unofficial_rgid_set) - set(album_df.loc[album_df["release_status_clean"] != "Official", "release_group_id"])

set()

Findings: A sanity check confirmed that the set of release\_group IDs flagged as unofficial aligns perfectly with the rows removed by filtering to release\_status\_clean == "Official" \(empty set difference\)\. In other words, the applied filter and the earlier diagnostic deletion list are fully consistent\. This confirms that no unofficial release groups remain in the album spine and that the QA logic is internally coherent\.

### III\.2 Cleaning up the Track DataFrame

Now, let's use the deletion list constructed in III\.1 to identify records to purge from the other tables\.

In [12]:
# Load the tracks dataframe

tracks_df = pd.read_csv("./pipeline/2.2.MUSICBRAINZ_mv_tmdb_soundtrack_track_spine_2015_2025.csv")
display(tracks_df.columns)
display(tracks_df.head())



Index(['tmdb_id', 'film_title', 'release_group_id', 'release_id',
       'match_method', 'album_us_release_date', 'us_date_has_missing_month',
       'us_date_has_missing_day', 'medium_id', 'disc_number', 'medium_format',
       'track_id', 'track_number', 'track_title', 'track_length_ms',
       'recording_id', 'recording_mbid', 'recording_title',
       'recording_length_ms', 'recording_artist_credit',
       'recording_first_release_year', 'recording_first_release_month',
       'recording_first_release_day', 'isrcs_text', 'recording_tags_text',
       'work_ids_text', 'work_titles_text', 'composer_names_text',
       'lyricist_names_text'],
      dtype='object')

,tmdb_id,film_title,release_group_id,release_id,match_method,album_us_release_date,us_date_has_missing_month,us_date_has_missing_day,medium_id,disc_number,medium_format,track_id,track_number,track_title,track_length_ms,recording_id,recording_mbid,recording_title,recording_length_ms,recording_artist_credit,recording_first_release_year,recording_first_release_month,recording_first_release_day,isrcs_text,recording_tags_text,work_ids_text,work_titles_text,composer_names_text,lyricist_names_text
0,158852,Tomorrowland,1527294,1608979,imdb_exact,2015-06-09,False,False,1692109,1,Digital Media,18687683,13,Frank Frank,78000.0,17796063,cb79d078-c57b-46a3-a09b-e3903e73aeb8,Frank Frank,78000.0,Michael Giacchino,NaN,NaN,NaN,USWD11570549,NaN,14179222,Frank Frank,Michael Giacchino,NaN
1,664425,Alone,4404592,5269969,title_contains_strict,NaN,NaN,NaN,5726478,1,CD-R,54208593,4,Isolate,140000.0,43561702,21fd6fb4-b461-4bd3-a12d-aaa01eee0d8d,Isolate,140000.0,Frederik Wiedmann,NaN,NaN,NaN,NaN,NaN,14876176,Isolate,Frederik Wiedmann,NaN
2,675799,Alone,4404592,5269969,title_contains_strict,NaN,NaN,NaN,5726478,1,CD-R,54208593,4,Isolate,140000.0,43561702,21fd6fb4-b461-4bd3-a12d-aaa01eee0d8d,Isolate,140000.0,Frederik Wiedmann,NaN,NaN,NaN,NaN,NaN,14876176,Isolate,Frederik Wiedmann,NaN
3,661950,Alone,4404592,5269969,title_contains_strict,NaN,NaN,NaN,5726478,1,CD-R,54208593,4,Isolate,140000.0,43561702,21fd6fb4-b461-4bd3-a12d-aaa01eee0d8d,Isolate,140000.0,Frederik Wiedmann,NaN,NaN,NaN,NaN,NaN,14876176,Isolate,Frederik Wiedmann,NaN
4,664425,Alone,4404592,5269969,title_contains_strict,NaN,NaN,NaN,5726478,1,CD-R,54208601,12,Screamers,162000.0,43561710,23437721-6ac1-44a1-9e92-59fb1a950fa5,Screamers,162000.0,Frederik Wiedmann,NaN,NaN,NaN,NaN,NaN,14876184,Screamers,Frederik Wiedmann,NaN


In [13]:
# Calculate the length BEFORE the deletion
tracks_before = len(tracks_df)

# Delete rows that contain the release group ids in the delete list
is_unofficial_track = tracks_df["release_group_id"].isin(unofficial_rgid_set)
deleted_track_ct = int(is_unofficial_track.sum())

tracks_official_df = tracks_df.loc[~is_unofficial_track].copy()

print(f"Tracks before: {tracks_before:,}")
print(f"Tracks deleted: {deleted_track_ct:,}")
print(f"Tracks after:  {len(tracks_official_df):,}")

tracks_official_df.to_csv(
    "./pipeline/3.2.Tracks_official_df.csv",
    index=False
)


Tracks before: 85,842
Tracks deleted: 2,968
Tracks after:  82,874


In [14]:
# For completeness, let's upload artist_df even though we don't need to deletion on it and save the output into
# the pipeline

artist_df = pd.read_csv("./pipeline/2.2.MUSICBRAINZ_mv_tmdb_soundtrack_artist_spine_2015_2025.csv")
artist_df.to_csv(
    "./pipeline/3.2.Artists_official_df.csv",
    index=False
)


### III\.3 Cleaning up the Wide DataFrame

In [15]:
# Load the wide dataframe

wide_df = pd.read_csv("./pipeline/2.2.MUSICBRAINZ_mv_tmdb_soundtrack_wide_track_2015_2025.csv")
display(wide_df.columns)
display(wide_df.head())



/tmp/ipykernel_241/1985245225.py:3: DtypeWarning: Columns (45,58,84) have mixed types. Specify dtype option on import or set low_memory=False.
  wide_df = pd.read_csv("./pipeline/2.2.MUSICBRAINZ_mv_tmdb_soundtrack_wide_track_2015_2025.csv")


Index(['tmdb_id', 'film_title', 'film_adult', 'film_runtime_min',
       'film_genres', 'film_rating', 'film_vote_count', 'film_mpaa_rating',
       'film_original_title', 'film_language_name', 'film_imdb_id',
       'film_wikidata_id', 'film_countries', 'film_year', 'film_release_date',
       'film_popularity', 'film_budget', 'film_revenue', 'film_studios',
       'film_director', 'film_soundtrack_composer_raw', 'film_top_cast',
       'film_keywords', 'film_ingested_at', 'release_group_id',
       'release_group_mbid', 'release_id', 'release_mbid', 'album_title',
       'rg_primary_type', 'rg_secondary_types', 'match_method',
       'album_soundtrack_type', 'album_notes', 'album_matched_at',
       'album_us_release_date', 'album_us_release_year',
       'album_us_release_month_min_observed',
       'album_us_release_day_min_observed', 'us_date_has_missing_month',
       'us_date_has_missing_day', 'us_any_event_missing_month',
       'us_any_event_missing_day', 'release_title', 'rel

,tmdb_id,film_title,film_adult,film_runtime_min,film_genres,film_rating,film_vote_count,film_mpaa_rating,film_original_title,film_language_name,film_imdb_id,film_wikidata_id,film_countries,film_year,film_release_date,film_popularity,film_budget,film_revenue,film_studios,film_director,film_soundtrack_composer_raw,film_top_cast,film_keywords,film_ingested_at,release_group_id,release_group_mbid,release_id,release_mbid,album_title,rg_primary_type,rg_secondary_types,match_method,album_soundtrack_type,album_notes,album_matched_at,album_us_release_date,album_us_release_year,album_us_release_month_min_observed,album_us_release_day_min_observed,us_date_has_missing_month,us_date_has_missing_day,us_any_event_missing_month,us_any_event_missing_day,release_title,release_status,release_packaging,barcode,release_language,release_script,release_comment,rg_tags_text,release_tags_text,label_names,label_mbids,label_tags_text,rg_rating,rg_rating_count,release_meta_date_added,release_meta_info_url,release_meta_amazon_asin,release_meta_cover_art_presence,album_artist_ids_text,album_artist_names_text,album_artist_mbids_text,album_artist_types_text,album_artist_max_film_ct_in_spine,album_artist_max_soundtrack_rg_ct_in_spine,medium_id,disc_number,medium_format,track_id,track_number,track_title,track_length_ms,recording_id,recording_mbid,recording_title,recording_length_ms,recording_artist_credit,isrcs_text,recording_first_release_year,recording_first_release_month,recording_first_release_day,recording_tags_text,work_ids_text,work_titles_text,composer_names_text,lyricist_names_text
0,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,tt21859110,NaN,United States of America,2022,2022-10-07,0.1425,0,0,"The Ninth House, MarVista Entertainment, Tubi",Brant Daugherty,Christopher French,"Novi Brown, Christopher Bencomo, Kimberly Daug...","stalker, survival, home invasion",2026-01-19 01:36:06.359 -0500,135013,fb75d93e-d99d-33c7-bd60-80e2228651d3,949340,40b79a4f-ca31-48fe-91a9-019c3c4eab5e,Alone in the Dark,NaN,Soundtrack,title_contains_strict,unknown,NaN,2026-01-25 03:07:30.754 -0500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alone in the Dark (disc 2),Official,NaN,NaN,English,Latin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01 07:09:43.921 -0400,NaN,NaN,absent,79164,Philippe Vachey,31056e50-d37d-461d-9c56-c1e2ad5ecf58,Person,1,1,949340,1,Mixed Mode CD,1106869,2,Alone in the Dark Theme,223066.0,1298993,bcb316f0-3f28-4a94-a087-db78d3a51fde,Alone in the Dark Theme,223066.0,Philippe Vachey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1027160,Alone in the Dark,False,90,"Horror, Thriller",4.769,13,NR,Alone in the Dark,English,tt21859110,NaN,United States of America,2022,2022-10-07,0.1425,0,0,"The Ninth House, MarVista Entertainment, Tubi",Brant Daugherty,Christopher French,"Novi Brown, Christopher Bencomo, Kimberly Daug...","stalker, survival, home invasion",2026-01-19 01:36:06.359 -0500,135013,fb75d93e-d99d-33c7-bd60-80e2228651d3,949340,40b79a4f-ca31-48fe-91a9-019c3c4eab5e,Alone in the Dark,NaN,Soundtrack,title_contains_strict,unknown,NaN,2026-01-25 03:07:30.754 -0500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alone in the Dark (disc 2),Official,NaN,NaN,English,Latin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01 07:09:43.921 -0400,NaN,NaN,absent,79164,Philippe Vachey,31056e50-d37d-461d-9c56-c1e2ad5ecf58,Person,1,1,949340,1,Mixed Mode CD,1106868,1,[data track],3620786.0,1298992,af02c70c-6c69-4c62-9f34-68a898c98402,[data track],3620786.0,Philippe Vachey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,322855,Shakedown,False,72,Documentary,5.038,14,NR,Shakedown,English,tt1794951,Q89668506,United States of America,2018,2018-02-17,0.4010,0,0,MEMORY,Leilah Weinraub,Tim Dewit,NaN,"strip club, los angeles, california, woman dir...",2026-01-19 01:36:05.812 -0500,165359,65314ddb-ab05-314e-bef9-b1372d825266,893204,7003024e-dea5-488a-8253-8b8042fc9eb9,Shakedown,Album,Soundtrack,title_contains_strict,unknown,NaN,2026-01-25 03:07:30.754 -0500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shakedo

In [16]:
# Calculate the length BEFORE the deletion
wide_before = len(wide_df)

# Delete rows that contain the release group ids in the delete list
is_unofficial_wide = wide_df["release_group_id"].isin(unofficial_rgid_set)
deleted_wide_ct = int(is_unofficial_wide.sum())

wide_official_df = wide_df.loc[~is_unofficial_wide].copy()

print(f"Records before: {wide_before:,}")
print(f"Records deleted: {deleted_wide_ct:,}")
print(f"Records after:  {len(wide_official_df):,}")

wide_official_df.to_csv(
    "./pipeline/3.2.Wide_official_df.csv",
    index=False
)


Records before: 85,842
Records deleted: 2,968
Records after:  82,874


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b124131d-2024-4253-bb46-8043aed4b78f' target="_blank">

Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>